spire-agent:
  image:
    registry: SSSSyour-registry.example.com
    repository: your-team/spire-agent
    tag: "1.8.5-customZZZZZZZZ"
  extraVolumes:
  - hello: world
    fred: jack
    word: up
  extraVolumeMounts:
  - word: up
  socketAlternate:
    image:
      registry: your-registry.example.com
      repository: your-team/bash
      tag: "1.8.5-custom"

