apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-chart.fullname" . }}
  labels:
    {{- if eq .Values.testIf.condition "hello" }}
    hello: world
    {{- else }}
    default: some default value
    {{- end}}
    {{- include "test-chart.labels" . | nindent 4 }}
data:
  app.yaml: |
    logLevel: {{ .Values.config.logLevel | quote }}
    featureFlags:
      audit: {{ .Values.config.featureFlags.audit }}
      metrics: {{ .Values.config.featureFlags.metrics }}
